project_name: mcdl

builds:
  - goos:
      - linux
    ldflags:
      - -X util.Version={{ .Version }}
      - -X main.date={{ .CommitDate }}
    mod_timestamp: '{{ .CommitTimestamp }}'

dockers:
  - image_templates:
      - "ghcr.io/voxelshift/{{.ProjectName}}:{{ .Tag }}"
      - "ghcr.io/voxelshift/{{.ProjectName}}:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/voxelshift/{{.ProjectName}}:{{ .Major }}"
      - "ghcr.io/voxelshift/{{.ProjectName}}:latest"
